### PR TITLE
Fix csv profile header

### PR DESCRIPTION
**Pull request by b4l**
Altitude header is missing in the `profile.csv` output.

### CODE REVIEW

**Review by ltshb — COMMENTED** [review]
Could you update the git commit message as defined in our guideline e.g.:
```text
Added missing `Altitude` header

Description of the issue, what is the problem when `Altitude` header is missing ?
```

**Comment by b4l** [comment]
@ltshb doone in https://github.com/geoadmin/service-alti/pull/91/commits/639535b6758a15bb9dec738ecceb31619b8e653f

**Review by ltshb — APPROVED** [review]
👍🏼

**Comment by ltshb** [comment]
Is there any JIRA ticket for this ? If yes could you add the jira ticket to the PR title, if no then leave as it is.

**Comment by b4l** [comment]
> Is there any JIRA ticket for this ? If yes could you add the jira ticket to the PR title, if no then leave as it is.

No, this is a upstream fix for NGM. Consider me a open source contributor.

**Pull request merged**
