### PR TITLE
Read posted data as text

### PR DESCRIPTION
**Pull request by gberaudo**
This PR should fix the profile when the body is the geometry as geojson (with content-type application/json).

### CODE REVIEW

**Comment by ltkum** [comment]
@gberaudo 
Hello, I'm investigating the tests at the moment. I established that, from our unit tests point of view, returning to the state of the application before your changes solve the tests issues, but I don't really know what you were expecting to solve with this.

Could you give me a full example of a query that did not go through when it should, or at least a full description of the problem at hand, so that I may ensure your problem is solved and the tests are able to go through ?

**Comment by gberaudo** [comment]
@ltkum, here is what I did:

cat data2.json 
{"type":"LineString","coordinates":[[2632092.1,1171169.9], [2632084.4,1171237.3]]}

`curl -H "Content-Type: application/json" -X POST -d @data2.json 'http://localhost:5000/rest/services/profile.json'`
=> using a fresh "develop" branch, it shows the following output in the server logs:
- with "linestring = request_object.get_data()" : no logs
- with "linestring = request_object.get_json()": " ERROR    - app.routes                 : the JSON object must be str, bytes or bytearray, not dict"

Interestingly, the request to the prod service works:
`curl -H "Content-Type: application/json" -X POST -d @data2.json https://api3.geo.admin.ch/rest/services/profile.json`

**Comment by pakb** [comment]
Should be covered by @ltkum 's work here : https://github.com/geoadmin/service-alti/pull/83

**Comment by ltkum** [comment]
Indeed, I'm closing the PR. Should there be a new problem, feel free to open a ticket. I'll be closing this issue.

**Comment by gberaudo** [comment]
Nice work, thanks @ltkum!

**Pull request closed without merging**
