### PR TITLE
BGDIINF_SB-1893: Made the number of wsgi worker configurable

### PR DESCRIPTION
**Pull request by ltshb**
Fixed a python3 issues with binary strings and did fixes some various issue for deployment on k8s.

### CODE REVIEW

**Review by ltclm — APPROVED** [review]
looks good to me from the diff.
how much memory is needed to preload the data in the cache?

**Comment by ltshb** [comment]
> looks good to me from the diff.
> how much memory is needed to preload the data in the cache?

That's a very good question ! I don't know, we will need to test/check it when we have the data migrated. There is currently 120 GB data on the file system, and I don't know how much memory we need to cache this data ? I cannot test it locally as I don't have enough disk space on my machine.

**Comment by ltclm** [comment]
in the filesystem we have:
```bash
$ du -sch kombo_2m_regio*
134G    kombo_2m_regio
134G    kombo_2m_regio_lv95
267G    insgesamt
```

i dont know if we can assign that much memory to 1..n pods

**Comment by ltshb** [comment]
I don't know the detailed implementation and if it is already cache in the prod instance, but for sure that something that we will need to check. But from what I've seen in the code, I think it doesn't cache all data files but only the index files which is less data.

**Pull request merged**
